name: franchise-nest

version: '3.8'

services:
  app:
    build:
      context: ../backend
      dockerfile: ../docker/backend.dev.Dockerfile
    container_name: nestjs_app
    working_dir: /app
    volumes:
      - ./../backend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=franchise
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 